---
- name: Update and upgrade apt packages
  hosts: all
  become: true

  tasks:
    - name: Update Packages via apt
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade Packages via apt
      ansible.builtin.apt:
        upgrade: "yes"
