---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  tasks:
    - name: Update Packages via apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      register: result
    - name: Display status
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"
    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      ansible.builtin.stat:
        path: /var/run/reboot-require
        get_checksum: false
      register: reboot_required_file
